name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake
    - name: Configure CMake
      run: cmake -B build
    - name: Build
      run: cmake --build build --config Release
